spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username: root
    password: 123456
    initialize: false

server:
  port: 8090

api:
  security:
    clientId: zhanchaoligeshoppingmall
    tokenSecret: shopping123
    tokenExpiresIn: 7200